name: D-day Alarm

on:
  schedule: #주기적으로 매일 23시에 실행 (UTC 표준 시간 기준)
    - cron: "0 23 * * *"
    
permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest # 코드를 실행할 가상환경 설정
    timeout-minutes: 1 # 타임 아웃 적용, 실행후 1분뒤에 자동 종료

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10 # 가상환경에 파이썬 설정
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies # 파이썬에서 사용하는 모듈들 설정
      run: |
        python -m pip install --upgrade pip
        python -m pip install discord
        python -m pip install pytz
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run python # 메인 코드 실행
      run: |
          python main.py

      
