client.run(TOKEN)```

```yml

name: D-day Alarm

on:
  schedule:
    - cron: "0 23 * * *"
    
permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install discord pytz
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run python
      run: |
        python main.py


      
